AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rasa_clean

  Sample SAM Template for rasa_clean

Parameters:
  PostgresHost:
    Type: String
    Default: localhost
  PostgresPort:
    Type: String
    Default: "5432"
  PostgresDatabase:
    Type: String
    Default: postgres
  PostgresUser:
    Type: String
    Default: postgres
  PostgresPassword:
    Type: String
    Default: "1234"
  Debug:
    Type: String
    Default: "true"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        POSTGRES_HOST: !Ref PostgresHost
        POSTGRES_PORT: !Ref PostgresPort
        POSTGRES_DATABASE: !Ref PostgresDatabase
        POSTGRES_USER: !Ref PostgresUser
        POSTGRES_PASSWORD: !Ref PostgresPassword
        DEBUG: !Ref Debug

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  PostFieldsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: api/modules/fields/insert_field.handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        PostFields:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fields
            Method: post
            
  SelectFieldsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: api/modules/fields/select_field.handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        GetFields:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fields
            Method: get

  PostFilesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: api/modules/files/post_files.handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        PostFiles:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /files
            Method: post


Outputs:
  PostFieldsFunction:
    Description: "Insert a new field: POST"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fields/"
  SelectFieldsFunction:
    Description: "Select fields by status, id or both: GET"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fields/"