AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rasa_clean

  Sample SAM Template for rasa_clean

Parameters:
  PostgresHost:
    Type: String
    Default: localhost
  PostgresPort:
    Type: String
    Default: "5432"
  PostgresDatabase:
    Type: String
    Default: postgres
  PostgresUser:
    Type: String
    Default: postgres
  PostgresPassword:
    Type: String
    Default: "1234"
  Debug:
    Type: String
    Default: "true"
  GrantType:
    Type: String
    Default: "1234"
  SecretKey:
    Type: String
    Default: "1234"
  ClientId:
    Type: String
    Default: "1234"
  ResourceId:
    Type: String
    Default: "1234"
  LoginUrl:
    Type: String
    Default: "1234"
  GroupId:
    Type: String
    Default: "1234"
  Token:
    Type: String
    Default: "1234"
  DashboardId:
    Type: String
    Default: "1234"
  DatasetId:
    Type: String
    Default: "1234"
  Bucket:
    Type: String
    Default: "1234"
  

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        POSTGRES_HOST: !Ref PostgresHost
        POSTGRES_PORT: !Ref PostgresPort
        POSTGRES_DATABASE: !Ref PostgresDatabase
        POSTGRES_USER: !Ref PostgresUser
        POSTGRES_PASSWORD: !Ref PostgresPassword
        DEBUG: !Ref Debug

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  PostFieldsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: api/modules/fields/insert_field.handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        PostFields:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fields
            Method: post

  PostFormsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: api/modules/forms/insert_form.handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        PostForms:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /forms
            Method: post

  PostFieldOptionsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: api/modules/field_options/insert_field_options.handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        PostForms:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{field_id}/options
            Method: post
            
  SelectFieldsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: api/modules/fields/select_field.handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        GetFields:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fields
            Method: get

  PostFilesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: api/modules/files/post_files.handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        PostFiles:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /files
            Method: post

  LoginMicrosoftFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: api/modules/esafe/authenticate.get_microsoft_token
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:
        Variables:
          GRANT_TYPE: !Ref GrantType
          SECRET_KEY: !Ref SecretKey
          CLIENT_ID: !Ref ClientId
          RESOURCE_ID: !Ref ResourceId
          LOGIN_URL: !Ref LoginUrl
          BUCKET: !Ref Bucket
      Events:
        EsafeAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get_auth_token
            Method: get
  
  GetDashboardData:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: api/modules/esafe/authenticate.get_power_bi_token
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:
        Variables:
          GROUP_ID: !Ref GroupId
          TOKEN: !Ref Token
          DASHBOARD_ID: !Ref DashboardId
          DATASET_ID: !Ref DatasetId
          BUCKET: !Ref Bucket
      Events:
        EsafeAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get_dashboard_token
            Method: get


Outputs:
  PostFieldsFunction:
    Description: "Insert a new field: POST"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fields/"
  PostFormsFunction:
    Description: "Insert a new form: POST"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/forms/"
  SelectFieldsFunction:
    Description: "Select fields by status, id or both: GET"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/files/"